CREATE DATABASE IF NOT EXISTS oclock CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE oclock;

CREATE TABLE IF NOT EXISTS alarms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    alarm_time TIME NOT NULL,
    message VARCHAR(255) NOT NULL,
    triggered BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);